### ISSUE TITLE
Handle missing foreign key references

### ISSUE THREAD

**Issue by nicksellen** [foodsharing-dev/foodsharing-api#1]
Foodsharing database has foreign key references that no longer exist. This happens if a user is deleted, all references to that user remain. This is sort of by intention and is not going to change (at least not right away) so needs to be handled here.

Currently doctrine will throw a big error in this case, but it seems there is a way to override this behaviour... the goal would be to have it so it behaves as if the foreign key was null.

**Comment by raph-ael** [comment]
What do you think abount writing an onDelete trigger and clean the database for now one time handy?
I could start doning this now!?

**Comment by nicksellen** [comment]
@NerdyProjects was thinking to write up a proposal on how to handle it last time I spoke to him... it would be useful to add any considerations here though... you know the database a lot better than me!

**Comment by NerdyProjects** [comment]
Missing foreign key references are existing for:

- users
- stores
- forum themes (user follow theme (forum))
- regions (theoretically - don't know when/if some got deleted)
(this list is maybe not complete)

where only users are a problem for now as stores are not deletable anymore and we currently only work on new pickups.

Desktop version uses implicit equijoins and sometimes inner joins, just very seldomly left joins. That means that normally content get hidden "automatically" although never defined.
After talking to kristijan, it is concluded:

- Forum messages should not be deleted and reference to deleted users should stay in tact. They should not be shown.
- Personal messages may reappear, but they also should not be deleted
- All user data should stay removed (well, obvious as we don't have it anyway)
- Other data is mostly don't care

As there is at least some data that should be kept, just using proper foreign keys with `on delete cascade` is not viable.
So I see soft deletes on the user as a good option and suggest
- adding a `deleted TINYINT(1)` column for the user (`fs_foodsaver`) table (as well as user archive)
- Put the user delete in a transation, leave current delete in tact and create a nulled/default entry with `deleted=1`
- Change the forum code (bezirk.model.php) to use `IF(fs.deleted = 1)` in `getThemes` and `getPosts` instead of the null check
- (optionally) add IF(fs.deleted=1) checks into loadConversationMessages to give an enhanced output but still no content (so basically same behaviour as now)
- When removing a user, also clean up `fs_betrieb_team`, `fs_apitoken`, `fs_basket_anfrage`, `fs_botschafter`, `fs_buddy`, `fs_event_has_wallpost`, `fs_event`, `fs_fairteiler_follower`, `fs_foodsaver_has_bell`, `fs_foodsaver_has_bezirk`, `fs_foodsaver_has_contact`, `fs_foodsaver_has_event`, `fs_foodsaver_has_fairteiler`, `fs_foodsaver_has_wallpost`, `fs_mailbox_member`, `fs_mailchange`, `fs_pass_gen`, `fs_pass_request`, `fs_quiz_session`, `fs_theme_follower`

NOT viable is removing entries in the `foodsaver_has_conversation` many to many table because after that, looking up a conversation for the new set of members (e.g. mostly just the user alone) could give this wrong ID. This problem of changing the context by changing group members is actually there always but would get much more relevant by this.

After that, do a cleanup pass on the table list where cleanup on delete happens.
After that, inserting deleted null users for userids gathered by querying `fs_foodsaver_has_conversation`, `fs_wallpost`, `fs_report`, `fs_rating`, `fs_abholer`

This should keep us consistent on the most currently displayed content while I also decided on keeping
- trust bananas
- wallposts on public things
- abuse reports
- pickups

Also it will fix the database maybe already for good - at least on the question of users.

**Comment by nicksellen** [comment]
Great work! 🥇 

Looks a bit painful, but definitely worth it.

I'm very sleepy, but a few thoughts/points/questions:

> deleted TINYINT(1)

`deleted_at somekindoftimestamp` perhaps? (but maybe the user archive table has that info)

> Put the user delete in a transation, leave current delete in tact and create a nulled/default entry with deleted=1

So:

stage | table | id | name | age | deleted
---|---|---|---|---|---
before soft delete | foodsaver | 5 | Peter | 20 | 0
after soft delete | foodsaver | 5 | _<null\|default>_ | _<null\|default>_ | 1
after soft delete | foodsaver archive | 5 | Peter | 20 | 1

> When removing a user, also clean up

Presumably deleting the entries for that user, but some of those things stay, like the wallposts, I guess the code already handles the case where the user is missing, but also if the link table entry is gone? (oh, wallpost is connected to user directly anyway...).

I didn't understand the bit about `foodsaver_has_conversation` wrong IDs. (As an aside, made me wonder whether the query in the new API will return details for members that wrote messages, but then left the conversation later).

How about adding foreign key constraints on the relevant tables to ensure it stays in order?

**Comment by NerdyProjects** [comment]
> `deleted_at somekindoftimestamp` perhaps? (but maybe the user archive table has that info)
Makes sense, user archive does not have this.

> Presumably deleting the entries for that user,
Yep, that's what I meant with cleanup. I chose the columns via a quick look at what is there, keeping for example wallposts (to be still able to display them for example on a public fairsharepoint wall).

The cleanedup (real deleted) columns should not delete any content that might be necessary to resolve some kind of issues/conflicts, so that a user in doubt just deletes their account and all is gone.

Conversations:
Imagine you (1) have some personal chats with 1 user(2).
Imagine, you(1) also have a group chat with users (2,3).
Now, user 3 gets removed. So your groupchat becomes (1,2) but as we don't have metadata on that, this is now the same as your personal chat with (2), meaning if you lookup a chat between (1,2), you might get that "old" group chat instead of your original private chat.

This risk is always there when people leave a group (which is actually not possible currently, but can happen in a store-team context that just uses auto-managed group chats), but the chance of it happening is much higher in that scenario.
Also, all your private chats with other users become chats with yourself when you remove one. You can always still access every single one with having the conversation list, but the lookup by participants might give strange results.

API for members that left conversation: No, I will file a bug on this.

Foreign key constraints:
Makes sense for all to be kept clean tables. Actually, I thought about doing it `on delete cascade` instead of PHP code.

@raph-ael what do you think on this? Because I would like to spend today on it.

**Comment by Sliverriver** [comment]
I tried to follow and understand so far. 
maybe who has deleted the user might also be helpfull to store somewhere (deleted by ).
If the users delets himself or from someone else (so far only orgateam/vorstand should be able to delete other users).
 
It might be usefull to keep the mails the users send - i guess that is stored in fs_mailchange ? 

Question regarding: 
- wallposts on public things
would that mean like the fair-teiler wall ? are there any other public walls ?
what about the own profile wall ?

**Comment by NerdyProjects** [comment]
It is not about providing new features, so the "deleted by" will not be implemented with this issue.
Mails would not be touched, I think I left them out of my proposal at all (so they would be kept).

I see the fairsharepoint wall as a public one. Profile: Hm, I dunno. Maybe best to remove those wallposts as well.

**Comment by Sliverriver** [comment]
ok - just crossed my mind since nick wrote something about adding the time. 

i think the post could be removed from the faresharepoint wall. 

what happens right now to the wall of a bezirk? do these remain or just hidden by accident?
what about the wall on a store ? it might have usefull information regarding the store or incidents.

**Comment by NerdyProjects** [comment]
So keep wallposts on store, remove them on bezirk? Wall has some different implementations - the general one will be fixed, others will be added as a bug report on desktop site.

**Comment by raph-ael** [comment]
Thank You for all the thought about that! I'm looking forward that everything works well after implementing this issue.

1.
I also think on update trigger / cascade is cleaner than make the ondelete stuff in the php code. Big task for all the tables (fs_betrieb_team, fs_apitoken, fs_basket_anfrage, fs_botschafter, fs_buddy, fs_event_has_wallpost, fs_event, fs_fairteiler_follower, fs_foodsaver_has_bell, fs_foodsaver_has_bezirk, fs_foodsaver_has_contact, fs_foodsaver_has_event, fs_foodsaver_has_fairteiler, fs_foodsaver_has_wallpost, fs_mailbox_member, fs_mailchange, fs_pass_gen, fs_pass_request, fs_quiz_session, fs_theme_follower)

2.
Is it really only the bezirk.model.php where we have to update the code? i think there are a lot of places in the code where are users listed, we have to look through all pages. But i'm happy to do this.

So go for it! Are you still on the way @NerdyProjects ? i can do it with you, maybe i do the stuff in the code and you the database updates? I will do tomorrow a bit for foodsharing and i have the whole friday to work on.

**Comment by NerdyProjects** [comment]
Yep if you look at the code, that's fine with me. At best start with the current master of the foodsharing repo, that is not (yet) deployed but I will have another look over the changes there as well.

No, it is not only bezirk model. There should be the place where the actual user is deleted.
Then the bezirk model for the forum posts and msg model for conversations. Also, all places where explicit INNER JOINS on fs_foodsaver are used seem reasonable to look at.

I suggest I do the database work until lunchtime today, by that I will generate a list of modules that don't need looking at.

**Comment by raph-ael** [comment]
okay, i pushed to master in gitlab. When i delete a user a have to give the table fs_foodsaver_archive also the new field "deleted"
